### ISSUE TITLE
Regarding the "test_manual_imrt_dose.txt" file

### ISSUE THREAD

**Issue by monjoybme** [nadeemlab/DoseRTX#16]
Hi,

Thanks for sharing your code. Could you tell a little bit about the "test_manual_imrt_dose.txt" file or share the file if available? 

[https://github.com/nadeemlab/DoseRTX/blob/main/statistics/compute_dvh_stats.py#L122](https://github.com/nadeemlab/DoseRTX/blob/main/statistics/compute_dvh_stats.py#L122)

Thanks in advance!

**Comment by sanadeem** [comment]
Unfortunately we can't share the file for the internal dataset which was used to train DoseRTX but you might want to check the public dataset available on our PortPy GitHub (https://github.com/PortPy-Project/PortPy).

@gourav3017 can you provide some details of the this file? And will similar information be available in the curated PortPy GitHub dataset?

**Comment by gourav3017** [comment]
Hi Monjoy,
This text file contains a list of patient IDs/MRNs for the test dataset. You can use your patient IDs for your tests. As Saad mentioned we cannot share this file since it contains patient MRN. If you have your own patients, you can input their ids in test_manual_imrt_dose.txt. For example
"Lung_patient_1_id
Lung_patient_2_id
Lung_Patient_3_id"

once you write those ids in text file, DoseRTX would compute dvh stats for each patient ids in the list. Let me know if there is any confusion

**Comment by monjoybme** [comment]
@gourav3017 @sanadeem Thanks a lot!
